services:
  epos:
    build: .
    image: epos
    container_name: epos
    restart: always
    platform: linux/amd64
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /srv:/srv
volumes:
  caddy_data:
  caddy_config:
